### ISSUE TITLE
How to use html2pdf.js without NPM or any other package manager.

### ISSUE THREAD

**Issue by sajidmanzoor10p** [eKoopmans/html2pdf.js#626]
Hello

How to use How to use html2pdf.js without NPM or any other package manager. I am working on a legacy project and need to use html2pdf.js with jQuery or Javascript. Please confirm how can I do that. 

I tried adding dependencies before html2pdf.js but it giving exception.
```
html2pdf.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'jsPDF')
    at ./src/plugin/jspdf-plugin.js (html2pdf.min.js:2:2378)
    at r (html2pdf.min.js:2:72332)
    at html2pdf.min.js:2:72910
    at html2pdf.min.js:2:73107
    at html2pdf.min.js:2:73120
    at html2pdf.min.js:2:303
    at html2pdf.min.js:2:328
```

Please confirm how can I use it without NPM. 

Thanks

**Comment by jonXmack** [comment]
https://github.com/eKoopmans/html2pdf.js#cdn

`<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`

**Comment by sajidmanzoor10p** [comment]
What if someone don't want to use CDN due to any reason?

**Comment by eKoopmans** [comment]
Looks like this is resolved, thanks.
