### ISSUE TITLE
Cannot read properties of undefined (reading 'createElementNS')

### ISSUE THREAD

**Issue by ivorycoast** [eKoopmans/html2pdf.js#640]
Hello guys,

I have this error from time to time :
`app.js:152655 
        
       TypeError: Cannot read properties of undefined (reading 'createElementNS')
    at 32.545fcf0d0c552b380b4c.js:2309:8282
    at 32.545fcf0d0c552b380b4c.js:2309:10029
    at 32.545fcf0d0c552b380b4c.js:2138:218
    at Object.<anonymous> (32.545fcf0d0c552b380b4c.js:2138:232)
    at ./node_modules/html2pdf.js/node_modules/jspdf/dist/jspdf.min.js (32.545fcf0d0c552b380b4c.js:2443:30)
    at __webpack_require__ (app.js:64:30)
    at 32.545fcf0d0c552b380b4c.js:16:35
    at Object.<anonymous> (32.545fcf0d0c552b380b4c.js:18:2)
    at ./node_modules/html2pdf.js/dist/html2pdf.js (32.545fcf0d0c552b380b4c.js:2127:30)
    at __webpack_require__ (app.js:64:30)`

Any idea guys?

Thanks!

**Comment by c3-anerishah** [comment]
@ivorycoast did you end up figuring this out? I'm running into the same thing.
